---
name: Check pre commit
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
    paths: ['**/*.py']
jobs:
  pre-commit:
    name: Check pre commit
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-pre-commit.yml
